name: Build UACME
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Compile uacme
        shell: cmd
        run: |
          cl /D_UNICODE /DUNICODE working-appinfo-uac.c /link rpcrt4.lib ntdll.lib advapi32.lib shlwapi.lib /SUBSYSTEM:WINDOWS /ENTRY:mainCRTStartup /out:uacme.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uacme-executable
          path: uacme.exe
